### PR TITLE
Fix the makefile

### PR DESCRIPTION
**Pull request by CRKatri**

### CODE REVIEW

**Comment by sunflsks** [comment]
This seems to fail to compile on my macOS machine, with it complaining that `libiosexec.a` does not exist. I'm no expert on proper Makefile syntax, so maybe I'm doing something wrong?

**Comment by CRKatri** [comment]
Can you copy and paste the exact message?

**Comment by sunflsks** [comment]
Here’s the full log:
```
cc    -c -o execl.o execl.c
cc    -c -o execv.o execv.c
cc    -c -o utils.o utils.c
execv.c:98:26: warning: assigning to 'char *' from 'const char *' discards qualifiers      [-Wincompatible-pointer-types-discards-qualifiers]
    argv_new[1 + offset] = path;
                         ^ ~~~~
1 warning generated.
cc  -DLIBIOSEXEC_INTERNAL -install_name /lib/libiosexec.1.dylib -shared -o libiosexec.1.dylib execl.o execv.o utils.o
ar cru libiosexec.a execl.o execv.o utils.o
libiosexec.a
make: libiosexec.a: No such file or directory
make: *** [libiosexec.a] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by sunflsks** [comment]
ty

**Pull request merged**
