### PR TITLE
correctly alloc argv size, set NULL for freed ptr

### PR DESCRIPTION
**Pull request by Torrekie**
this fixes bug #13 

tested on iOS 14.5.1

I forgot why I added 2 in that calloc btw, can anyone tell me

### CODE REVIEW

**Comment by badger200** [comment]
I fixed this last year in my personal libiosexec source by simply changing the oddly arbitrary 1024 in the calloc to ARG_MAX which is defined as 262144 in `#include <sys/syslimits.h>` (which must be added atop this get argv .c file).

But for some reason I got a lot of opposition here and nobody seemed to understand the problem; I compile large projects like the entire LLVM source on a frequent basis, and this quickly causes crashes in libiosexec simply because it invokes commands with large arguments > 1024 bytes, which is really small compared to ARG_MAX 262144...

In practical terms, this meant any command longer than perhaps "1 screenful" of arguments, would crash. From memory the first one I always hit was the command that links libLLVMSupport.a, as the command includes a long list of object files.

But I also recall crashes in autotools/autoconf identical to the example you mention in #13.

PS: I just searched and ProcursusTeam actually deleted all my comments I made here at the time, it was incredibly strange behavior to me as I didn't think I said anything offensive?

**Comment by CRKatri** [comment]
I'm sorry you got ignored in the past, I'll take some time later today to make libiosexec dynamically resize argv so that we can fix your issue and not be allocating a full `ARG_MAX` when unneeded.

**Comment by badger200** [comment]
@CRKatri Thanks, I appreciate that! Yes I'm very happy with this solution. Looking forward to be able to just use libiosexec straight from git as-is.

**Comment by Torrekie** [comment]
fixed in cfae759

**Pull request closed without merging**
