### PR TITLE
add ie_uname

### PR DESCRIPTION
**Pull request by Torrekie**
Changes:
1. While calling `uname()` on embedded Darwin systems, it returns an unexpected `HW_MACHINE` result (`uname -m` returns product identifiers `HW_PRODUCT` rather than machine classes on iOS which resulting a wrong machine detection), let's force it return `arm64`.

### CODE REVIEW

**Comment by Diatrus** [comment]
I have 2 concerns:

1. when compiling Procursus, the compiler should (in a percect world and most worlds) have compiler-rt. This patch shouldn’t be needed?

2. I’m not directly opposed to a uname patch, but do you know if there is a good reason it’s returning HW identifiers? Or is it truly a bug? I’m also concerned about the licensing of the code snippet you included.

**Comment by Torrekie** [comment]
Compilers do have compiler-rt, but `__clear_cache` was something required at runtime.
While attempting to compile `__builtin___clear_cache` for iOS, builtin check passes, but no `___clear_cache` symbol found in libSystem
```
TorrekiedeMacBook-Pro:test_clear_cache torrekie$ xcrun --sdk iphoneos cc test.c
Undefined symbols for architecture arm64:
  "___clear_cache", referenced from:
      _main in test-0f2158.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
macOS and iOS both have `/usr/lib/system/libcompiler_rt.dylib`, the library which should be somewhere including `__clear_cache` (defined at llvm/compiler-rt/lib/builtins/clear_cache.c), but the one for iOS seems did not include this clear cache shortcut at all
```
TorrekiedeMacBook-Pro:~ torrekie$ nm ~/ios14.2-sharedcache/usr/lib/system/libcompiler_rt.dylib | grep "cache"
TorrekiedeMacBook-Pro:~ torrekie$ nm /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libcompiler_rt.tbd | grep "cache"
0000000000000000 S $ld$hide$os10.4$___clear_cache
0000000000000000 S $ld$hide$os10.5$___clear_cache
0000000000000000 S ___clear_cache
0000000000000000 S $ld$hide$os10.4$___clear_cache
0000000000000000 S $ld$hide$os10.5$___clear_cache
0000000000000000 S ___clear_cache
0000000000000000 S $ld$hide$os10.4$___clear_cache
0000000000000000 S $ld$hide$os10.5$___clear_cache
0000000000000000 S ___clear_cache
```
Normally we can directly use this on macOS without additional libraries (since libcompiler_rt.dylib has been reexported by libSystem.dylib), we haven't found this issue before because Procursus set `-undefined dynamic_lookup` as default. I thought if we are linking everything to libiosexec, supply some missing functions are actually feasible.

`uname()` are having different returns since Apple wants to deprecate old `HW_MACHINE`, and they do returning different values on embedded Darwins than macOS does.
```
/*
 * CTL_HW identifiers
 */
#define HW_MACHINE       1              /* string: machine class (deprecated: use HW_PRODUCT) */
#define HW_MODEL         2              /* string: specific machine model (deprecated: use HW_TARGET) */
```
On macOS (Apple M1):
```
TorrekiedeMacBook-Pro:Procursus torrekie$ sysctl -n hw.machine
arm64
TorrekiedeMacBook-Pro:Procursus torrekie$ uname -m
arm64
```
On iOS (iPhone 12 mini):
```
iPhone:~ root# sysctl -n hw.machine
iPhone13,1
iPhone:~ root# uname -m
iPhone13,1
```
On x86_64 Debian:
```
root@growing-silo-1:~# uname -m
x86_64
```
This weird behavior are causing many problems, programs using `uname()` to detect machine infos are getting unexpected results
On iOS:
```
iPhone:~ root# python3.9
Python 3.9.7 (default, Sep 24 2021, 16:34:22) 
[Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
'iPhone13,1'
```
On macOS:
```
TorrekiedeMacBook-Pro:~ torrekie$ python3.9
Python 3.9.9 (main, Nov 21 2021, 03:16:13) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
'arm64'
```

the original source of uname.c are from [Apple's libc](https://opensource.apple.com/source/Libc/Libc-1439.141.1/gen/uname.c), should follow APSL 2.0

**Comment by CRKatri** [comment]
`compiler-rt` is not dynamically loaded, it is a static archive provided by the toolchain. `/usr/lib/system/libcompiler_rt.dylib` is used by the system for some internal use, but not for us to touch. Looking at the `clang_rt` in the Xcode toolchain, the static library that provides symbols used by `clang` for `@available` and such, `___clear_cache` seems to only be in the arm64e slice.

**Comment by CRKatri** [comment]
`uname(3)` has a very vague definition in POSIX, the standard says that it will return `Name of the hardware type on which the system is running.`, which imho it is doing by returning the hardware identifier (https://man.cameronkatri.com/POSIX-2017/man0p/sys_utsname.h.0p). The standard itself mentions that it is not portable, because of this I don't think adding `ie_uname` is needed.

**Pull request closed without merging**
